"""add indexes and unique constraints

Revision ID: 485caa5d5a6f
Revises: ffbc860ace91
Create Date: 2026-05-07 13:45:20.175442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485caa5d5a6f'
down_revision: Union[str, Sequence[str], None] = 'ffbc860ace91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_att_enter_time_status', 'attendances', ['enter_time', 'status'], unique=False)
    op.create_index(op.f('ix_attendances_status'), 'attendances', ['status'], unique=False)
    op.create_index(op.f('ix_cameras_login'), 'cameras', ['login'], unique=False)
    op.create_unique_constraint(None, 'cameras', ['ip_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cameras', type_='unique')
    op.drop_index(op.f('ix_cameras_login'), table_name='cameras')
    op.drop_index(op.f('ix_attendances_status'), table_name='attendances')
    op.drop_index('ix_att_enter_time_status', table_name='attendances')
    # ### end Alembic commands ###
