"""add work_schedule

Revision ID: abfd3cf37961
Revises: 485caa5d5a6f
Create Date: 2026-05-07 17:11:45.025299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abfd3cf37961'
down_revision: Union[str, Sequence[str], None] = '485caa5d5a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('work_schedule',
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('late_threshold_minutes', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('early_leave_threshold_minutes', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Singleton: insert default row so the rest of the app can assume it exists.
    op.execute(
        "INSERT INTO work_schedule (id, start_time, end_time, "
        "late_threshold_minutes, early_leave_threshold_minutes) "
        "VALUES (1, '09:00', '18:00', 0, 0)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_schedule')
    # ### end Alembic commands ###
