"""Initial migration

Revision ID: ffbc860ace91
Revises: 
Create Date: 2026-05-07 10:49:52.234821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbc860ace91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('enter', 'exit', name='camera_type'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=False),
    sa.Column('camera_user_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_camera_user_id'), 'employees', ['camera_user_id'], unique=True)
    op.create_table('attendances',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('enter_camera_id', sa.Integer(), nullable=True),
    sa.Column('enter_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enter_rec_no', sa.Integer(), nullable=True),
    sa.Column('exit_camera_id', sa.Integer(), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_rec_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'LEFT_EARLY', name='attendancestatus'), nullable=False),
    sa.Column('presence_status', sa.Enum('COMPLETE', 'NO_EXIT', 'NO_ENTRY', name='presencestatus'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['enter_camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['exit_camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enter_camera_id', 'enter_rec_no', name='uq_attendances_enter_cam_rec'),
    sa.UniqueConstraint('exit_camera_id', 'exit_rec_no', name='uq_attendances_exit_cam_rec')
    )
    op.create_index(op.f('ix_attendances_employee_id'), 'attendances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendances_enter_rec_no'), 'attendances', ['enter_rec_no'], unique=False)
    op.create_index(op.f('ix_attendances_enter_time'), 'attendances', ['enter_time'], unique=False)
    op.create_index(op.f('ix_attendances_exit_rec_no'), 'attendances', ['exit_rec_no'], unique=False)
    op.create_index(op.f('ix_attendances_exit_time'), 'attendances', ['exit_time'], unique=False)
    op.create_index(op.f('ix_attendances_presence_status'), 'attendances', ['presence_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendances_presence_status'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_exit_time'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_exit_rec_no'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_enter_time'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_enter_rec_no'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_employee_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_employees_camera_user_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('cameras')
    # ### end Alembic commands ###
